// src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { path, navigate } from './router';
  import { fade, fly } from 'svelte/transition';
  import Router from './Router.svelte';
  import Title from './components/Title.svelte';
  import Menu from './components/Menu.svelte';
  import Checker from './components/Checker.svelte';
  import Activity from './components/Activity.svelte';
  import Suggestion from './components/Suggestion.svelte';
  import TypingText from './components/TypingText.svelte';
  import SplashScreen from './components/SplashScreen.svelte';
  import CyberpunkCity from './components/CyberpunkCity.svelte';
  import pages from './configs/pages.json';
  import titles from './configs/titles.json';

  // State
  let gameMode = false;
  let isContentVisible = true;
  let checker = false;
  let activity = false;
  let joke = false;
  let showHint = false;
  let showSplash = true;
  let containerRef: HTMLElement;
  let cyberpunkCity: CyberpunkCity;

  // Computed
  $: visiblePages = pages.filter((p: any) => !p.hidden);
  $: noFootersShowing = !activity && !checker && !joke;

  // Methods
  function toggleContent() {
    isContentVisible = !isContentVisible;
  }

  function startExploration() {
    if (cyberpunkCity) cyberpunkCity.startExplorationMode();
  }

  function startFlyingTour() {
    if (cyberpunkCity) cyberpunkCity.startFlyingTour();
  }

  function handleKeydown(e: KeyboardEvent) {
      if (gameMode) return;

      if (e.key === "Escape") {
          const gameRoutes = ['/game', '/noughts-and-crosses', '/checker', '/ask'];
          if (gameRoutes.includes($path)) {
              navigate('/hidden');
          }
      }

      switch (e.key) {
          case "ArrowRight": {
              const currentIndex = visiblePages.findIndex((page: any) => page.link === $path);
              if (currentIndex !== -1 && currentIndex < visiblePages.length - 1) {
                  navigate(visiblePages[currentIndex + 1].link);
              }
              break;
          }
          case "ArrowLeft": {
              const currentIndex = visiblePages.findIndex((page: any) => page.link === $path);
              if (currentIndex > 0) {
                  navigate(visiblePages[currentIndex - 1].link);
              }
              break;
          }
      }
  }

  // Lifecycle
  let splashTimeout: any;
  let hintTimeout1: any;
  let hintTimeout2: any;

  onMount(() => {
    splashTimeout = setTimeout(() => showSplash = false, 500);
    hintTimeout1 = setTimeout(() => showHint = true, 2000);
    hintTimeout2 = setTimeout(() => showHint = false, 5000);

    // Input detection for sticky hover fix
    let lastTouchTime = 0;
    const onTouchStart = () => {
        lastTouchTime = Date.now();
        document.body.classList.remove('can-hover');
    };
    const onMouseMove = () => {
        if (Date.now() - lastTouchTime > 500) {
            document.body.classList.add('can-hover');
        }
    };
    document.body.addEventListener('touchstart', onTouchStart);
    document.body.addEventListener('mousemove', onMouseMove);

    window.addEventListener('keydown', handleKeydown);

    return () => {
        document.body.removeEventListener('touchstart', onTouchStart);
        document.body.removeEventListener('mousemove', onMouseMove);
    };
  });

  onDestroy(() => {
    clearTimeout(splashTimeout);
    clearTimeout(hintTimeout1);
    clearTimeout(hintTimeout2);
    if (typeof window !== 'undefined') window.removeEventListener('keydown', handleKeydown);
  });

  // Watch route for title update
  $: {
    if (typeof document !== 'undefined') {
        let pageTitle = '404';
        const p = $path;

        if (p === '/noughts-and-crosses') pageTitle = 'Noughts and Crosses';
        else if (p === '/game') pageTitle = 'Catch the Button!';
        else if (p === '/checker') pageTitle = 'Checker';
        else if (p === '/ask') pageTitle = 'Ask Me';
        else {
            let routeName = '';
            if (p === '/') routeName = 'home';
            else {
                const parts = p.split('/').filter(Boolean);
                if (parts.length === 1) routeName = parts[0];
            }

            if (routeName) {
                const currentPage = pages.find((page: any) =>
                    routeName === 'home' ? page.link === '/' : page.link.slice(1) === routeName
                );
                if (currentPage) pageTitle = currentPage.title;
            }
        }
        document.title = "Elliot > " + pageTitle;
    }
  }
</script>

<div id="content-wrapper" class:fade-out={gameMode}>
  <nav>
    <Title
        title={titles.title}
        subtitle={titles.subtitle}
        {activity}
        {joke}
        on:activity={() => activity = !activity}
        on:joke={() => joke = !joke}
    />
    <Menu
        pages={visiblePages}
        contentVisible={isContentVisible}
        on:explore={startExploration}
        on:fly={startFlyingTour}
        on:toggle-content={toggleContent}
    />
  </nav>

  <div class="router-view-container" bind:this={containerRef}>
      {#if isContentVisible}
        {#key $path}
            <div class="router-transition-wrapper" in:fly={{ y: 20, duration: 500 }} out:fly={{ y: -20, duration: 500 }}>
                <Router />
            </div>
        {/key}
      {/if}
  </div>

  {#if noFootersShowing && showHint && isContentVisible}
      <!-- svelte-ignore a11y-click-events-have-key-events -->
      <!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
      <footer transition:fade on:click={() => checker = !checker} class="content-container">
          <TypingText text="The titles might be clickable..." />
      </footer>
  {/if}
</div>

<CyberpunkCity
    bind:this={cyberpunkCity}
    on:game-start={() => gameMode = true}
    on:game-end={() => gameMode = false}
/>

{#if checker}
    <div transition:fade class="overlay-container" class:fade-out={gameMode}>
        <Checker />
    </div>
{/if}
{#if activity}
    <div transition:fade class="overlay-container" class:fade-out={gameMode}>
        <Activity />
    </div>
{/if}
{#if joke}
    <div transition:fade class="overlay-container" class:fade-out={gameMode}>
        <Suggestion url="https://icanhazdadjoke.com/" valueName="joke" title="Have a laugh!" />
    </div>
{/if}
{#if showSplash}
    <div transition:fade class="overlay-container">
        <SplashScreen />
    </div>
{/if}

<style>
.title {
  margin-bottom: 0;
}

.fade-out {
  opacity: 0;
  pointer-events: none;
  transition: opacity 2s ease;
}

.overlay-container {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
    z-index: 100;
}
.overlay-container > :global(*) {
    pointer-events: auto;
}

/* Transitions are handled by Svelte `transition:fade` and `fly` */

.router-transition-wrapper {
    position: absolute;
    width: 100%;
}
</style>

// app.vue
<template>
  <div id="content-wrapper" :class="{ 'fade-out': gameMode }">
    <nav>
      <Title
        :title="titles.title"
        :subtitle="titles.subtitle"
        :activity="activity"
        :joke="joke"
        @activity="toggleActivity"
        @joke="toggleJoke"
      />
      <Menu 
        :pages="visiblePages" 
        :content-visible="isContentVisible"
        @explore="startExploration" 
        @fly="startFlyingTour" 
        @demo="startDemoMode"
        @toggle-content="toggleContent"
      />
    </nav>
    <Transition name="cyberpunk-glitch">
      <div class="router-view-container" ref="containerRef" v-show="isContentVisible">
        <NuxtPage
          :transition="{
            name: transitionName,
            onBeforeLeave,
            onEnter,
            onAfterEnter,
            mode: 'out-in'
          }"
        />
      </div>
    </Transition>
    <Transition name="fade">
      <footer
        v-if="noFootersShowing && showHint"
        v-show="isContentVisible"
        @click="checker = !checker"
        class="content-container"
      >
        <TypingText text="The titles might be clickable..." />
      </footer>
    </Transition>
  </div>

  <ClientOnly>
    <CyberpunkCity ref="cyberpunkCityRef" @game-start="gameMode = true" @game-end="gameMode = false" />
  </ClientOnly>

  <Transition name="fade">
    <Checker v-if="checker" :class="{ 'fade-out': gameMode }" />
  </Transition>
  <Transition name="fade">
    <Activity v-show="activity" :class="{ 'fade-out': gameMode }" />
  </Transition>
  <Transition name="fade">
    <Suggestion
      v-show="joke"
      :class="{ 'fade-out': gameMode }"
      url="https://icanhazdadjoke.com/"
      valueName="joke"
      title="Have a laugh!"
    />
  </Transition>
  <Transition name="glitch-fade">
    <SplashScreen v-if="showSplash" />
  </Transition>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed, watch, onErrorCaptured } from "vue";
import { useRoute, useRouter } from "vue-router";
import Title from "~/components/Title.vue";
import Menu from "~/components/Menu.vue";
import Checker from "~/components/Checker.vue";
import Activity from "~/components/Activity.vue";
import Suggestion from "~/components/Suggestion.vue";
import TypingText from "~/components/TypingText.vue";
import SplashScreen from "~/components/SplashScreen.vue";
import CyberpunkCity from "~/components/CyberpunkCity.vue";
import pages from "~/configs/pages.json";
import titles from "~/configs/titles.json";
import { Page } from "~/interfaces/Page";

const visiblePages = computed(() => {
  return pages.filter((page: Page) => !page.hidden);
});

const containerRef = ref<HTMLElement | null>(null);
const checker = ref(false);
const activity = ref(false);
const joke = ref(false);
const showHint = ref(false);
const showSplash = ref(true);
const route = useRoute();
const router = useRouter();
const transitionName = ref("cards");
const gameMode = ref(false);
const isContentVisible = ref(true);

function toggleContent() {
  isContentVisible.value = !isContentVisible.value;
}

const cyberpunkCityRef = ref<any>(null);

function startExploration() {
  if (cyberpunkCityRef.value && cyberpunkCityRef.value.startExplorationMode) {
    cyberpunkCityRef.value.startExplorationMode();
  }
}

function startFlyingTour() {
  if (cyberpunkCityRef.value && cyberpunkCityRef.value.startFlyingTour) {
    cyberpunkCityRef.value.startFlyingTour();
  }
}

function startDemoMode() {
  if (cyberpunkCityRef.value && cyberpunkCityRef.value.startDemoMode) {
    cyberpunkCityRef.value.startDemoMode();
  }
}

function handleKeydown(e: KeyboardEvent) {
  if (gameMode.value) return;

  if (e.key === "Escape") {
    const gameRoutes = ['/game', '/noughts-and-crosses', '/checker', '/ask'];
    if (gameRoutes.includes(route.path)) {
      router.push('/hidden');
    }
  }

  switch (e.key) {
    case "ArrowRight": {
      const currentIndex = visiblePages.value.findIndex((page: Page) => page.link === route.path);
      if (currentIndex !== -1 && currentIndex < visiblePages.value.length - 1) {
        router.push(visiblePages.value[currentIndex + 1].link);
      }
      break;
    }
    case "ArrowLeft": {
      const currentIndex = visiblePages.value.findIndex((page: Page) => page.link === route.path);
      if (currentIndex > 0) {
        router.push(visiblePages.value[currentIndex - 1].link);
      }
      break;
    }
  }
}

function onBeforeLeave(el: Element) {
  if (containerRef.value) {
    const { height } = getComputedStyle(el);
    containerRef.value.style.height = height;
  }
}

function onEnter(el: Element) {
  if (containerRef.value) {
    const { height } = getComputedStyle(el);
    containerRef.value.style.height = height;
  }
}

function onAfterEnter() {
  if (containerRef.value) {
    containerRef.value.style.height = "";
  }
}

function getPageIndex(routeName: any) {
  if (routeName === "/") {
    return pages.findIndex((page) => page.link === "/");
  }

  const index = pages.findIndex((page) => page.link.slice(1) === routeName);
  return index === -1 ? Object.keys(pages).length : index;
}

const noFootersShowing = computed(() => {
  return !activity.value && !checker.value && !joke.value;
});

function toggleActivity() {
  activity.value = !activity.value;
}

function toggleJoke() {
  joke.value = !joke.value;
}

let splashTimeout: ReturnType<typeof setTimeout>;

onMounted(() => {
  splashTimeout = setTimeout(() => {
    showSplash.value = false;
  }, 500);

  setTimeout(() => {
    showHint.value = true;
  }, 2000);

  setTimeout(() => {
    showHint.value = false;
  }, 5000);

  // Input detection for sticky hover fix
  let lastTouchTime = 0;

  document.body.addEventListener('touchstart', () => {
    lastTouchTime = Date.now();
    document.body.classList.remove('can-hover');
  });

  document.body.addEventListener('mousemove', () => {
    if (Date.now() - lastTouchTime > 500) {
      document.body.classList.add('can-hover');
    }
  });

  window.addEventListener("keydown", handleKeydown);
});

onErrorCaptured((err) => {
  console.error("App Error Captured:", err);
  showSplash.value = false;
  return true;
});

onUnmounted(() => {
  clearTimeout(splashTimeout);
  window.removeEventListener("keydown", handleKeydown);
});

watch(
  () => route.path,
  (newPath, oldPath) => {
    if (oldPath) {
      const oldPageIndex = getPageIndex(oldPath.slice(1));
      const newPageIndex = getPageIndex(newPath.slice(1));

      transitionName.value = newPageIndex > oldPageIndex ? 'cards' : 'cards-reverse';
    }

    let pageTitle;

    switch (newPath) {
      case '/noughts-and-crosses':
        pageTitle = 'Noughts and Crosses';
        break;
      case '/game':
        pageTitle = 'Catch the Button!';
        break;
      case '/checker':
        pageTitle = 'Checker';
        break;
      case '/ask':
        pageTitle = 'Ask Me';
        break;
      default: {
        let routeName;
        if (route.params.name) {
          routeName = route.params.name;
        } else if (newPath === '/') {
          routeName = 'home';
        }

        if (routeName) {
          let currentPage;
          if (routeName === 'home') {
            currentPage = pages.find((page) => page.link === '/');
          } else {
            currentPage = pages.find((page) => page.link.slice(1) === routeName);
          }
          pageTitle = currentPage ? currentPage.title : '404';
        } else {
          pageTitle = '404';
        }
        break;
      }
    }

    useHead({
        title: "Elliot > " + pageTitle
    });
  },
  { immediate: true },
);
</script>

<style>
.title {
  margin-bottom: 0;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.fade-out {
  opacity: 0;
  pointer-events: none;
  transition: opacity 2s ease;
}

/* Glitch Fade Transition for Splash Screen */
.glitch-fade-leave-active {
  animation: glitch-fade-out 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

@keyframes glitch-fade-out {
  0% {
    opacity: 1;
    transform: translate(0);
    clip-path: inset(0 0 0 0);
  }
  10% {
    opacity: 1;
    transform: translate(-2px, 2px);
    clip-path: inset(10% 0 80% 0);
  }
  20% {
    opacity: 1;
    transform: translate(2px, -2px);
    clip-path: inset(80% 0 10% 0);
  }
  30% {
    opacity: 1;
    transform: translate(-2px, 2px);
    clip-path: inset(10% 0 80% 0);
  }
  40% {
    opacity: 1;
    transform: translate(2px, -2px);
    clip-path: inset(80% 0 10% 0);
  }
  50% {
    opacity: 1;
    transform: translate(-2px, 2px);
    clip-path: inset(10% 0 80% 0);
  }
  60% {
    opacity: 1;
    transform: translate(2px, -2px);
    clip-path: inset(80% 0 10% 0);
  }
  70% {
    opacity: 1;
    transform: translate(-2px, 2px);
    clip-path: inset(10% 0 80% 0);
  }
  80% {
    opacity: 1;
    transform: translate(2px, -2px);
    clip-path: inset(80% 0 10% 0);
  }
  90% {
    opacity: 1;
    transform: translate(-2px, 2px);
    clip-path: inset(10% 0 80% 0);
  }
  100% {
    opacity: 0;
    transform: translate(0);
    clip-path: inset(0 0 0 0);
  }
}

</style>

<style>
.cyberpunk-glitch-enter-active {
  animation: glitch-in 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

.cyberpunk-glitch-leave-active {
  animation: glitch-out 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

@keyframes glitch-in {
  0% {
    opacity: 0;
    transform: scaleY(0.1) skewX(20deg);
    filter: hue-rotate(90deg);
    clip-path: inset(50% 0 50% 0);
  }
  20% {
    opacity: 1;
    transform: scaleY(0.4) skewX(-10deg);
    clip-path: inset(20% 0 30% 0);
  }
  60% {
    transform: scaleY(1.1) skewX(5deg);
    clip-path: inset(0 0 0 0);
  }
  100% {
    opacity: 1;
    transform: scaleY(1) skewX(0);
    filter: hue-rotate(0deg);
  }
}

@keyframes glitch-out {
  0% {
    opacity: 1;
    transform: scaleY(1) skewX(0);
    clip-path: inset(0 0 0 0);
  }
  40% {
    transform: scaleY(1.1) skewX(-5deg);
    clip-path: inset(10% 0 10% 0);
  }
  80% {
    opacity: 0.5;
    transform: scaleY(0.2) skewX(40deg);
    clip-path: inset(40% 0 40% 0);
  }
  100% {
    opacity: 0;
    transform: scaleY(0.1) skewX(60deg);
    clip-path: inset(50% 0 50% 0);
  }
}
</style>
