// src/components/Activity.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fade } from 'svelte/transition';

  let activity: any = null;
  let loading = false;
  let hideHint = false;

  async function fetchActivity() {
      loading = true;
      try {
          const response = await fetch("https://bored.api.lewagon.com/api/activity");
          activity = await response.json();
      } catch (error) {
          console.error(error);
      } finally {
          loading = false;
      }
  }

  function newSuggestion() {
      fetchActivity();
      if (!hideHint) hideHint = true;
  }

  onMount(fetchActivity);
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
<footer
  on:click={newSuggestion}
  style:cursor={loading ? 'progress' : ''}
  class="content-container"
>
  {#if activity}
    <article title="Click for a new suggestion" class="marginless">
      <header>
        <strong>
          Try this {activity.type} activity
        </strong>
        (The Bored API)
      </header>
      <p class="marginless">{activity.activity}</p>
    </article>
  {:else}
    <article class="marginless">
      <header>
        <strong>Try this activity</strong>
      </header>
      <p class="marginless" aria-busy="true">
        Loading from The Bored API.
      </p>
    </article>
  {/if}

  {#if !hideHint}
    <div transition:fade>
      <article style="padding-top: 0; margin-top: 0; margin-bottom: 0">
        <footer style="font-style: oblique; font-size: 0.8em; margin-top: 0">
          Click to update
        </footer>
      </article>
    </div>
  {/if}
</footer>

// components/Activity.vue
<template>
  <footer
    @click="newSuggestion"
    :style="{ cursor: loading ? 'progress' : '' }"
    class="content-container"
  >
    <article v-if="activity" title="Click for a new suggestion" style="margin-bottom: 0">
      <header>
        <strong>
          Try this {{ activity.type }} activity
        </strong>
        (The Bored API)
      </header>
      <p class="marginless">{{ activity.activity }}</p>
    </article>
    <article v-else style="margin-bottom: 0">
      <header>
        <strong>Try this activity</strong>
      </header>
      <p class="marginless" aria-busy="true">
        Loading from The Bored API.
      </p>
    </article>
    <Transition name="fade">
      <article v-if="!hideHint" style="padding-top: 0; margin-top: 0; margin-bottom: 0">
        <footer style="font-style: oblique; font-size: 0.8em; margin-top: 0">
          Click to update
        </footer>
      </article>
    </Transition>
  </footer>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";

/**
 * @file Activity.vue
 * @description A component that fetches and displays a random activity suggestion from The Bored API.
 * It shows a loading state and allows users to fetch a new suggestion by clicking on it.
 */

/**
 * @type {import('vue').Ref<any>}
 * @description A reactive reference to the activity object fetched from the API.
 * It is null until the first activity is fetched.
 */
const activity = ref<any>(null);

/**
 * @type {import('vue').Ref<boolean>}
 * @description A reactive reference to indicate if an activity is currently being fetched.
 */
const loading = ref(false);

/**
 * @type {import('vue').Ref<boolean>}
 * @description A reactive reference to control the visibility of the "Click to update" hint.
 * It becomes true after the first user-initiated suggestion fetch.
 */
const hideHint = ref(false);

/**
 * @description Fetches a random activity from The Bored API and updates the component's state.
 * Sets the loading state during the fetch operation.
 * @returns {Promise<void>} A promise that resolves when the activity has been fetched and state updated.
 */
async function fetchActivity() {
  loading.value = true;
  try {
    const response = await fetch("https://bored.api.lewagon.com/api/activity");
    activity.value = await response.json();
  } catch (error) {
    console.error(error);
  } finally {
    loading.value = false;
  }
}

/**
 * @description Initiates fetching a new activity suggestion and hides the hint text.
 */
function newSuggestion() {
  fetchActivity();
  if (!hideHint.value) {
    hideHint.value = true;
  }
}

/**
 * @description A Vue lifecycle hook that fetches an initial activity when the component is mounted.
 */
onMounted(fetchActivity);
</script>
