// src/components/PageContent.svelte
<script lang="ts">
  import { fade } from 'svelte/transition';
  import Paragraph from './Paragraph.svelte';
  import pages from '../configs/pages.json';

  export let name: string;

  let showHint = false;

  // Compute resolvedPage reactive to `name`
  $: resolvedPage = (() => {
      // name is from router logic:
      // / -> name='home'
      // /:name -> name=params.name
      // 404 -> name='404'

      if (name === 'home') return pages.find((p: any) => p.link === '/');
      if (name === '404') return null;

      const found = pages.find((p: any) => p.link.slice(1) === name);
      // If not found and not explicitly 404, we might default or show 404.
      // Vue logic was: if route.params.name -> find page. if not found -> undefined.
      // If route.params.pathMatch -> null.
      // If none (route.path === '/') -> pages[0].

      // With my router:
      // / -> name='home'
      // /:name -> name=foo

      if (found) return found;

      // If name is home but not found (unlikely), fallback to pages[0]
      if (name === 'home') return pages[0];

      return null;
  })();

  function handleMouseDown() {
    showHint = true;
    setTimeout(() => showHint = false, 500);
  }
</script>

<main>
  <section>
    <article class="marginless">
      <header>
        <!-- svelte-ignore a11y-no-noninteractive-element-interactions -->
        <h2 class="title" on:mousedown={handleMouseDown}>
          {#if resolvedPage}
            {resolvedPage.title}
            {#if showHint}
              <span transition:fade
                style="font-weight: 100; font-style: italic; font-size: 0.6em; vertical-align: middle;">
                - Nothing here
              </span>
            {/if}
          {:else}
            404 - Page not found
          {/if}
        </h2>
      </header>
      {#if resolvedPage}
        {#each resolvedPage.body as paragraph, index}
          <Paragraph
            {paragraph}
            last={index + 1 === resolvedPage.body.length}
          />
        {/each}
      {:else}
        <Paragraph
          paragraph={`The page <strong>${name}</strong> does not exist!`}
          last={true}
        />
      {/if}
    </article>
  </section>
</main>

// src/components/PageContent.tsx
import { createSignal, createMemo, Show, For } from "solid-js";
import { useParams, useLocation } from "@solidjs/router";
import pages from "../configs/pages.json";
import Paragraph from "./Paragraph";
import { Page } from "../interfaces/Page";

interface PageContentProps {
  name?: string;
}

export default function PageContent(props: PageContentProps) {
  const [showHint, setShowHint] = createSignal(false);
  const params = useParams();
  const location = useLocation();

  const page = createMemo(() => {
    // Determine the name based on props or params
    const routeName = props.name || params.name;

    if (routeName) {
      if (routeName === "home") {
        return pages.find((p: Page) => p.link === "/");
      }
      return pages.find((p: Page) => p.link.slice(1) === routeName);
    }

    if (location.pathname !== "/") {
      return null;
    }

    return pages[0];
  });

  function handleMouseDown() {
    showHint(true);
    setTimeout(() => {
      setShowHint(false);
    }, 500);
  }

  return (
    <main>
      <section>
        <article class="marginless">
          <header>
            <h2 class="title" onMouseDown={handleMouseDown}>
              <Show
                when={page()}
                fallback={<>404 - Page not found</>}
              >
                <Show when={page()?.icon}>
                  <span class="page-icon">{page()?.icon} </span>
                </Show>
                {page()?.title}
                <Show when={showHint()}>
                  <span
                    class="fade-enter-active"
                    style={{
                      "font-weight": "100",
                      "font-style": "italic",
                      "font-size": "0.6em",
                      "vertical-align": "middle",
                    }}
                  >
                    - Nothing here
                  </span>
                </Show>
              </Show>
            </h2>
          </header>
          <Show
            when={page()}
            fallback={
              <Paragraph
                paragraph={`The page <strong>${params.name || props.name}</strong> does not exist!`}
                last={true}
              />
            }
          >
            <For each={page()?.body}>
              {(paragraph, index) => (
                <Paragraph
                  paragraph={paragraph}
                  last={index() + 1 === page()?.body.length}
                />
              )}
            </For>
          </Show>
        </article>
      </section>
    </main>
  );
}
